=== grycap/gpf4med/gpf4med-core/src/main/xsd/report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:annotation>
		<xs:documentation>Reporting</xs:documentation>
	</xs:annotation>
	
	<xs:element name="DICOM_SR" 	 	type="Document"		/>
	<xs:element name="DICOM_REPORTS" 	type="Documents"    />
	
	
	<xs:complexType name="UnitMeasurement">
		<xs:sequence>
			<xs:element name="CODE_VALUE" 			type="xs:string" />
			<xs:element name="CODE_SCHEMA"			type="xs:string" />
			<xs:element name="CODE_MEANING"			type="xs:string" />
			<xs:element name="CODE_MEANING2"		type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Value">
		<xs:sequence>
			<xs:element name="CODE_VALUE" 			type="xs:string" />
			<xs:element name="CODE_SCHEMA"			type="xs:string" />
			<xs:element name="CODE_MEANING"			type="xs:string" />
			<xs:element name="CODE_MEANING2"		type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Num">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME" 	type="ConceptName" 	   />
			<xs:element name="UNIT_MEASUREMENT"	type="UnitMeasurement" />
			<xs:element name="VALUE"			type="xs:string"	   />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Code">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME" type="ConceptName" />
			<xs:element name="VALUE"		type="Value"	   />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Date">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME" type="ConceptName"  />
			<xs:element name="VALUE"		type="xs:string"	/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Text">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME" type="ConceptName" 	/>
			<xs:element name="VALUE"		type="xs:string"	/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ChildrenDepth3">
		<xs:sequence>
			<xs:element name="TEXT"			type="Text" 	 		minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="CODE" 		type="Code" 	 		minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="NUM" 			type="Num" 	 			minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ContainerDepth3">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME"		type="ConceptName" 		 />
			<xs:element name="CHILDREN"			type="ChildrenDepth3"    />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ChildrenDepth2">
		<xs:sequence>
			<xs:element name="TEXT"			type="Text" 	 		minOccurs="0" maxOccurs="unbounded" />			
			<xs:element name="CODE" 		type="Code" 	 		minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="NUM" 			type="Num" 	 			minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="CONTAINER" 	type="ContainerDepth3" 	maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="ContainerDepth2">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME"		type="ConceptName" 		 />
			<xs:element name="CHILDREN"			type="ChildrenDepth2"    />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ChildrenDepth1">
		<xs:sequence>
			<xs:element name="TEXT"			type="Text" 	 		minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="CODE" 		type="Code" 	 		minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="NUM" 			type="Num" 	 			minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="CONTAINER" 	type="ContainerDepth2" 	maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ContainerDepth1">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME"		type="ConceptName" />
			<xs:element name="CHILDREN"			type="ChildrenDepth1"    />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ChildrenDepth0">
		<xs:sequence>
			<xs:element name="TEXT"			type="Text" 	 		minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="DATE"			type="Date" 	 		minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="CONTAINER" 	type="ContainerDepth1" 	maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ConceptName">
		<xs:sequence>
			<xs:element name="CODE_VALUE" 			type="xs:string" />
			<xs:element name="CODE_SCHEMA"			type="xs:string" />
			<xs:element name="CODE_MEANING"			type="xs:string" />
			<xs:element name="CODE_MEANING2"		type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ContainerDepth0">
		<xs:sequence>
			<xs:element name="CONCEPT_NAME"		type="ConceptName" 		 />
			<xs:element name="CHILDREN"			type="ChildrenDepth0"    />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Document">
		<xs:sequence>
			<xs:element name="CONTAINER" 		type="ContainerDepth0" />			 
		</xs:sequence>
		<xs:attribute name="IDReport" 			type="xs:string" />
		<xs:attribute name="IDOntology" 		type="xs:string" />
		<xs:attribute name="DateTimeStart" 		type="xs:string" />
		<xs:attribute name="DateTimeEnd" 		type="xs:string" />
		<xs:attribute name="IDTRENCADISReport" 	type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="Documents">
		<xs:sequence>
			<xs:element name="DICOM_SR" type="Document" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== grycap/gpf4med/gpf4med-core/src/main/xml/generatedReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<DICOM_SR DateTimeEnd="" DateTimeStart="" IDOntology="" IDReport="" IDTRENCADISReport="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/report.xsd">
  <CONTAINER>
    <CONCEPT_NAME>
      <CODE_VALUE>CODE_VALUE</CODE_VALUE>
      <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
      <CODE_MEANING>CODE_MEANING</CODE_MEANING>
      <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
    </CONCEPT_NAME>
    <CHILDREN>
      <TEXT>
        <CONCEPT_NAME>
          <CODE_VALUE>CODE_VALUE</CODE_VALUE>
          <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
          <CODE_MEANING>CODE_MEANING</CODE_MEANING>
          <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
        </CONCEPT_NAME>
        <VALUE>VALUE</VALUE>
      </TEXT>
      <DATE>
        <CONCEPT_NAME>
          <CODE_VALUE>CODE_VALUE</CODE_VALUE>
          <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
          <CODE_MEANING>CODE_MEANING</CODE_MEANING>
          <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
        </CONCEPT_NAME>
        <VALUE>VALUE</VALUE>
      </DATE>
      <CONTAINER>
        <CONCEPT_NAME>
          <CODE_VALUE>CODE_VALUE</CODE_VALUE>
          <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
          <CODE_MEANING>CODE_MEANING</CODE_MEANING>
          <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
        </CONCEPT_NAME>
        <CHILDREN>
          <TEXT>
            <CONCEPT_NAME>
              <CODE_VALUE>CODE_VALUE</CODE_VALUE>
              <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
              <CODE_MEANING>CODE_MEANING</CODE_MEANING>
              <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
            </CONCEPT_NAME>
            <VALUE>VALUE</VALUE>
          </TEXT>
          <CODE>
            <CONCEPT_NAME>
              <CODE_VALUE>CODE_VALUE</CODE_VALUE>
              <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
              <CODE_MEANING>CODE_MEANING</CODE_MEANING>
              <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
            </CONCEPT_NAME>
            <VALUE>
              <CODE_VALUE>CODE_VALUE</CODE_VALUE>
              <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
              <CODE_MEANING>CODE_MEANING</CODE_MEANING>
              <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
            </VALUE>
          </CODE>
          <NUM>
            <CONCEPT_NAME>
              <CODE_VALUE>CODE_VALUE</CODE_VALUE>
              <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
              <CODE_MEANING>CODE_MEANING</CODE_MEANING>
              <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
            </CONCEPT_NAME>
            <UNIT_MEASUREMENT>
              <CODE_VALUE>CODE_VALUE</CODE_VALUE>
              <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
              <CODE_MEANING>CODE_MEANING</CODE_MEANING>
              <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
            </UNIT_MEASUREMENT>
            <VALUE>VALUE</VALUE>
          </NUM>
          <CONTAINER>
            <CONCEPT_NAME>
              <CODE_VALUE>CODE_VALUE</CODE_VALUE>
              <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
              <CODE_MEANING>CODE_MEANING</CODE_MEANING>
              <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
            </CONCEPT_NAME>
            <CHILDREN>
              <TEXT>
                <CONCEPT_NAME>
                  <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                  <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                  <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                  <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                </CONCEPT_NAME>
                <VALUE>VALUE</VALUE>
              </TEXT>
              <CODE>
                <CONCEPT_NAME>
                  <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                  <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                  <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                  <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                </CONCEPT_NAME>
                <VALUE>
                  <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                  <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                  <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                  <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                </VALUE>
              </CODE>
              <NUM>
                <CONCEPT_NAME>
                  <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                  <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                  <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                  <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                </CONCEPT_NAME>
                <UNIT_MEASUREMENT>
                  <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                  <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                  <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                  <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                </UNIT_MEASUREMENT>
                <VALUE>VALUE</VALUE>
              </NUM>
              <CONTAINER>
                <CONCEPT_NAME>
                  <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                  <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                  <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                  <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                </CONCEPT_NAME>
                <CHILDREN>
                  <TEXT>
                    <CONCEPT_NAME>
                      <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                      <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                      <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                      <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                    </CONCEPT_NAME>
                    <VALUE>VALUE</VALUE>
                  </TEXT>
                  <CODE>
                    <CONCEPT_NAME>
                      <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                      <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                      <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                      <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                    </CONCEPT_NAME>
                    <VALUE>
                      <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                      <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                      <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                      <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                    </VALUE>
                  </CODE>
                  <NUM>
                    <CONCEPT_NAME>
                      <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                      <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                      <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                      <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                    </CONCEPT_NAME>
                    <UNIT_MEASUREMENT>
                      <CODE_VALUE>CODE_VALUE</CODE_VALUE>
                      <CODE_SCHEMA>CODE_SCHEMA</CODE_SCHEMA>
                      <CODE_MEANING>CODE_MEANING</CODE_MEANING>
                      <CODE_MEANING2>CODE_MEANING2</CODE_MEANING2>
                    </UNIT_MEASUREMENT>
                    <VALUE>VALUE</VALUE>
                  </NUM>
                </CHILDREN>
              </CONTAINER>
            </CHILDREN>
          </CONTAINER>
        </CHILDREN>
      </CONTAINER>
    </CHILDREN>
  </CONTAINER>
</DICOM_SR>
